# Generated by Django 4.2.9 on 2024-02-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_options_alter_coupon_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupon',
            table=None,
        ),
    ]
