# Generated by Django 4.2.9 on 2024-02-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Назваие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ('title',),
            },
        ),
    ]
