# Generated by Django 4.2.9 on 2024-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productspecifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecifications',
            name='description',
            field=models.CharField(blank=True, verbose_name='Описание'),
        ),
    ]
